services:
  - type: web
    name: verballink-translator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run source/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    plan: free 