services:
  - type: web
    name: verballink-translator
    env: python
    buildCommand: |
      sudo apt-get update 
      sudo apt-get install -y portaudio19-dev python3-all-dev libsndfile1 libasound2-dev
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run source/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: free 